### ISSUE TITLE
WebContainer won't start, not a 3rd party cookie issue

### ISSUE THREAD

**Issue by technovangelist** [sveltejs/learn.svelte.dev#95]
Trying to view learn.svelte.dev but getting the Failed to start webcontainer error. I have followed the instructions for enabling 3rd party cookies. Turned off every security feature possible in Chrome, Arc, and Firefox. Disabled pi.hole and even tethered on my phone to bypass my network. Tried a second computer. Always getting the same error in the browser. In console I see: 

`Access to fetch at 'https://w-corp.staticblitz.com/fs_bg.f78fa732fec6c779d7f25afc3bb0f5f1091671ec.wasm' from origin 'https://learnsveltedev-r4j5.w-corp.staticblitz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

and also 

`Failed to load resource: net::ERR_FAILED`

**Comment by EricSimons** [comment]
Hey all! Eric from the StackBlitz side here, I just circled with the team and confirmed this is an issue on our side. It looks like a large upgrade we just rolled out missed some cross origin CDN caching properly for WC API usage. FYI that we just deployed a fix and all should be working again. 🙌  Will make sure we get testing in place to ensure future updates won't break API consumers as well, especially as we target moving from private alpha to public beta soon here. Thanks again for flagging this and sorry about the inconvenience!

**Comment by Conduitry** [comment]
I'm still getting missing CORS headers on the response for https://w-corp.staticblitz.com/fs_bg.f78fa732fec6c779d7f25afc3bb0f5f1091671ec.wasm - should I keep being patient for something to update?

**Comment by EricSimons** [comment]
Can you try doing a hard reload and/or disabling/clearing browser cache? (Assuming you haven't tried yet)

**Comment by Conduitry** [comment]
I've done both. Here's a copy of the cURL from the request from browser dev tools:

```
$ curl -I 'https://w-corp.staticblitz.com/fs_bg.f78fa732fec6c779d7f25afc3bb0f5f1091671ec.wasm' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://learnsveltedev-r4j5.w-corp.staticblitz.com/' -H 'Origin: https://learnsveltedev-r4j5.w-corp.staticblitz.com' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'TE: trailers'
HTTP/2 200
date: Mon, 29 Aug 2022 21:03:14 GMT
content-type: application/wasm
last-modified: Fri, 26 Aug 2022 11:58:55 GMT
etag: W/"ef48e349bd69977db2bd202960eacfa1"
cache-control: public, max-age=31557600
x-cache: Hit from cloudfront
via: 1.1 d671204b8bf6c2b9056c338588204020.cloudfront.net (CloudFront)
x-amz-cf-pop: EWR52-C1
x-amz-cf-id: 0zXP1ZsSC5AMw3Ya0fZ-Pa-IA7b-tynhSjuMznigOkO4TlVcx5Ct0w==
age: 8420
cross-origin-embedder-policy: require-corp
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: cross-origin
cf-cache-status: HIT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=dCMHYqpbUlnfs1AzRKOqQywu1EhdMYg%2F3UxkBci3OxFvatv%2Fg1xLgmYkdmoMKWClojOUSNhRSp9ykyxkeqNJ1xvvgeG4idj82Ao3dD6Nt%2F5W4Ga1Fq5F%2Fywq%2Frpq4LKVkWY1PxfIghsv"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
vary: Accept-Encoding
strict-transport-security: max-age=15552000; includeSubDomains
server: cloudflare
cf-ray: 74283b731ebd8c4d-EWR
content-encoding: br
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

which makes me think that if this is getting cached, it's not on my end.

**Comment by apai4** [comment]
Thanks for your patience with this. It looks like this was due to some caching issues after our latest CDN changes were deployed on the StackBlitz side. We've invalidated this URL on our CDN from our cache again just now. Would you be able to try again and see if the issue still persists?

**Comment by Conduitry** [comment]
Same thing in the browser; still no `access-control-allow-origin` header when I hit it directly with the above cURL.

**Comment by Conduitry** [comment]
_Something_ just happened. With the above cURL I was briefly getting the headers

```
access-control-allow-origin: https://vitejs-vite-hbwcyi.w-corp.staticblitz.com
access-control-allow-methods: GET
access-control-allow-credentials: true
```

(i.e., present, but for the wrong origin), and then they went away.

**Comment by EricSimons** [comment]
We've been investigating internally and it seems like we're seeing varied results from cloudfront- for example currently working in Chrome but not Firefox on my machine, but both have been working on and off intermittently. 🤔 

We just reverted to a previous WebContainer build on prod which will update the asset URLs, so if there's an issue CDN propagation/cache this could/should fix the issue. Will report back once it's live in ~10m so we can test further.

**Comment by EricSimons** [comment]
Deploy is live- seems like it's consistently returning the proper assets now across browsers. Can y'all open again w/ cache disable and see if the same is showing on your side?

(One thing to note is that this previous build of WebContainer has a larger payload footprint that is fixed in the latest build, once we cut the next release today/tomorrow it'll automatically update here as well)

**Comment by Conduitry** [comment]
Looks good to me. I just disabled the cache and hit refresh several times, and I was consistently getting assets (build hash `968a32de9d01484de0feb027dd69dcf18139a386`) that the browser was able to access.

I do note however that they are no longer cross-origin requests. The WASM files lived on the same domain as the iframe requesting them, so, unless something else has been fixed, I assume this error might come back if you switched back to serving them from different domains.

**Comment by EricSimons** [comment]
Yeah you are correct, that was part of the large infra change we made recently for how webcontainer assets are hosted. Our team is going to investigate further tomorrow and see if we can reproduce this and make any necessary fixes before cutting the next release, as it seems like there might be some regression with the CDN configuration. Really strange that cloudfront was giving such erratic hits/misses.

For good measure we'll circle back here once we address the CDN's root cause and deploy the latest release to verify it works properly for y'all.

Thank you again for all of your help debugging this btw, we really appreciate it! ❤️

**Comment by EricSimons** [comment]
Just circling back here- we've had the latest deployed for a few weeks now and all seems to work well, so this should be good to close now!

**Comment by Conduitry** [comment]
Yup, looks good to me! Closing.
